apiVersion: v1
kind: Namespace
metadata:
  name: test-external
  labels:
    example: network-validation
---
apiVersion: v1
kind: Pod
metadata:
  name: external-pod
  namespace: test-external
  labels:
    example: network-validation
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: internal-pod
  namespace: sandbox-my-first-test-9pcg9
  labels:
    example: network-validation
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"