  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: supabase
    namespace: argocd
  spec:
    project: default

    sources:
      - repoURL: https://supabase-community.github.io/supabase-kubernetes
        chart: supabase
        targetRevision: 0.5.1
        helm:
          valueFiles:
            - $values/k8s-manifests/supabase/values.yaml

      - repoURL: https://github.com/rgunasekaran-github/k3s-terraform-ansible.git
        targetRevision: main
        ref: values

    destination:
      server: https://kubernetes.default.svc
      namespace: supabase

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true